agregator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('news.urls', 'news'), namespace='news'))
]

news/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.main, name='main'),
    path('<int:post_id>', views.post, name='post')
]

news/models.py
from django.db import models


class Category(models.Model):
    category = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category


class News(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    site = models.URLField()
    title = models.CharField(max_length=300)
    picture = models.URLField()
    logo = models.URLField()
    description = models.TextField()
    date = models.DateTimeField(auto_now=False)

    def __str__(self):
        return self.date.strftime("%d-%m-%Y | %H:%M")

news/views.py
from django.shortcuts import render
from news.async_parser.gather_data_technologies import main_technologies
from news.async_parser.gather_data_science import main_science

from news.models import News


def main(request):
    news = News.objects.all().order_by('date').reverse()[0:15]
    r_news = News.objects.order_by('?')[0:20]

    if request.method == 'POST':

        # Ajax запускает обновление каждые 5 минут
        if request.POST.get('Refresh'):
            main_science()
            main_technologies()

        # Ловим запрос перехода на вкладку "Наука"
        elif request.POST.get('Science'):
            science = News.objects.filter(category__category='Наука').order_by('date').reverse()
            r_news = News.objects.filter(category__category='Наука').order_by('?')

            # Получаем список источников в категории "Наука"
            list_of_science = []
            for new in News.objects.filter(category__category='Наука'):
                list_of_science.append(new.name)

            # Получаем список источников в категории "Технологии"
            list_of_technology = []
            for new in News.objects.filter(category__category='Технологии'):
                list_of_technology.append(new.name)

            context = {'news': science, 'r_news': r_news, 'list_of_science': set(list_of_science), 'list_of_technology': set(list_of_technology)}
            return render(request, 'news/main.html', context)

        # Ловим запрос перехода на вкладку "Наука"
        elif request.POST.get('Technologies'):
            technologies = News.objects.filter(category__category='Технологии').order_by('date').reverse()
            r_news = News.objects.filter(category__category='Технологии').order_by('?')

            # Получаем список источников в категории "Наука"
            list_of_science = []
            for new in News.objects.filter(category__category='Наука'):
                list_of_science.append(new.name)

            # Получаем список источников в категории "Технологии"
            list_of_technology = []
            for new in News.objects.filter(category__category='Технологии'):
                list_of_technology.append(new.name)

            context = {'news': technologies, 'r_news': r_news, 'list_of_science': set(list_of_science), 'list_of_technology': set(list_of_technology)}
            return render(request, 'news/main.html', context)

        # Попытка отображения всех новостей
        elif request.POST.get('More'):
            news = News.objects.all().order_by('date').reverse()
            r_news = News.objects.order_by('?')

            # Получаем список источников в категории "Наука"
            list_of_science = []
            for new in News.objects.filter(category__category='Наука'):
                list_of_science.append(new.name)

            # Получаем список источников в категории "Технологии"
            list_of_technology = []
            for new in News.objects.filter(category__category='Технологии'):
                list_of_technology.append(new.name)

            context = {'news': news, 'r_news': r_news, 'list_of_science': set(list_of_science), 'list_of_technology': set(list_of_technology)}
            return render(request, 'news/main.html', context)

        # Ловим запрос на сортировку источников
        elif dict(request.POST).get('dropdown'):
            search = []
            for i in dict(request.POST).get('dropdown'):
                search.append(News.objects.filter(name=i))
            context = {'news': search}
            return render(request, 'news/search.html', context)

    # Получаем список источников в категории "Наука"
    list_of_science = []
    for new in News.objects.filter(category__category='Наука'):
        list_of_science.append(new.name)

    # Получаем список источников в категории "Технологии"
    list_of_technology = []
    for new in News.objects.filter(category__category='Технологии'):
        list_of_technology.append(new.name)

    context = {'news': news, 'r_news': r_news, 'list_of_science': set(list_of_science), 'list_of_technology': set(list_of_technology)}
    return render(request, 'news/main.html', context)

# Отображение поста
def post(request, post_id):
    new = News.objects.get(id=post_id)
    r_news = News.objects.order_by('?')
    context = {'new': new, 'r_news': r_news[0:4]}
    return render(request, 'news/post.html', context)

news/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
   <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/96/96343.png" type="image/png">
  <style>
    .logo:hover {
      /* Start the shake animation and make the animation last for 0.5 seconds */
      animation: shake 0.5s;

      /* When the animation is finished, start again */
      animation-iteration-count: infinite;
    }

    @keyframes shake {
      0% { transform: translate(1px, 1px) rotate(0deg); }
      10% { transform: translate(-1px, -2px) rotate(-1deg); }
      20% { transform: translate(-3px, 0px) rotate(1deg); }
      30% { transform: translate(3px, 2px) rotate(0deg); }
      40% { transform: translate(1px, -1px) rotate(1deg); }
      50% { transform: translate(-1px, 2px) rotate(-1deg); }
      60% { transform: translate(-3px, 1px) rotate(0deg); }
      70% { transform: translate(3px, 1px) rotate(-1deg); }
      80% { transform: translate(-1px, -1px) rotate(1deg); }
      90% { transform: translate(1px, 2px) rotate(0deg); }
      100% { transform: translate(1px, -2px) rotate(-1deg); }
    }
  </style>
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-md bg-light navbar-light">
  <a class="navbar-brand" href="{% url 'news:main' %}">Agregator(all news)</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <form class="mx-auto" method="post">
      {% csrf_token %}
      <ul class="navbar-nav">
        <li class="nav-item mr-5">
          <button class="nav-link btn btn-link" name="Technologies" value="technologies">Технологии</button>
        </li>
        <li class="nav-item mr-5">
          <button class="nav-link btn btn-link" name="Science" value="science">Наука</button>
        </li>
        <li class="nav-item mr-5">
          {% block dropdown %}
          {% endblock %}
        </li>
      </ul>
    </form>
  </div>
</nav>
  <main role="main">
    <div class="album py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            {% block main_content %}
            {% endblock %}
          </div>
          <div class="col-md-4">
            {% block second_content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
{% block scripts %}
{% endblock %}
</script>
</body>
</html>

news/templates/news/main.html
{% extends 'news/base.html' %}

{% block title %}Agregator{% endblock %}

{% block dropdown %}
<div class="dropdown">
  <button type="button" class="nav-link btn btn-link dropdown-toggle" data-toggle="dropdown">
  Все источники
  </button>
    {% csrf_token %}
    <form method="post">
        <div class="dropdown-menu">
          <h5 class="dropdown-header">Технологии</h5>
            {% for name in list_of_technology %}
            <small><label class="checkbox" style="margin: 5px;"><input style="margin: 5px;" type="checkbox" name="dropdown" value="{{ name }}">{{ name }}</label></small><br>
            {% endfor %}
            <br>
            <h5 class="dropdown-header">Наука</h5>
            {% for name in list_of_science %}
            <small><label class="checkbox" style="margin: 5px;"><input style="margin: 5px;" type="checkbox" name="dropdown" value="{{ name }}">{{ name }}</label></small><br>
            {% endfor %}
            <br>
          <input class="btn btn-link mx-auto d-block" type="submit" value="Применить">
        </div>
    </form>
{% endblock %}

{% block main_content %}
{% for new in news %}
<div class="card mb-4 bg-light">
  <a href="{% url 'news:post' new.id %}"><img class="bd-placeholder-img card-img-top img-rounded" width="80%"  src="{{ new.picture }}"></a>
  <div class="card-body">
    <a href="{{ new.site }}" target="_blank"><img class="mx-auto d-block logo" src="{{ new.logo }}" width="40%"></a>
    <hr width="80%" align="center">
    <p class="card-text"><a href="{% url 'news:post' new.id %}" target="_blank"><h3 align="center"><b>{{new.title}}</b></h3></a></p>
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        <a href="{% url 'news:post' new.id %}" target="_blank"><button type="button" class="btn btn-sm btn-outline-secondary">Узнать больше</button></a>
      </div>
      <small class="text-muted">{{ new }}</small>
    </div>
  </div>
</div>
{% endfor %}
    <form method="post">
      {% csrf_token %}
      <button class="btn btn-secondary mx-auto d-block" value="more" name="More">Загрузить еще</button>
      <hr>
    </form>
{% endblock %}


{% block second_content %}
{% for new in r_news %}
<div class="card mb-4 bg-light">
  <a href="{% url 'news:post' new.id %}"><img class="bd-placeholder-img card-img-top img-rounded" width="80%" style="max-width: 360px; max-height: 265px;"  src="{{ new.picture }}"></a>
  <div class="card-body">
    <a href="{{ new.site }}" target="_blank"><img class="mx-auto d-block logo" src="{{ new.logo }}" width="40%"></a>
    <hr width="80%" align="center">
    <p class="card-text"><a href="{% url 'news:post' new.id %}" target="_blank"><h6 align="center"><b>{{new.title}}</b></h6></a></p>
    <h6 align="center"><small class="text-muted">{{ new }}</small></h6>
  </div>
</div>
{% endfor %}
{% endblock %}

{% block scripts %}
var s = function doAjax() {
      $.ajax({
              type: 'POST',
              url: 'http://127.0.0.1:8000/',
              data: {'csrfmiddlewaretoken': '{{ csrf_token }}', 'Refresh': 'refresh'},
              dataType: 'json',
              success: function (data) {
              $('#hidden').val(data);
              }
      })};
 setInterval(s,300000);
{% endblock %}

news/templates/news/post.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
    .logo:hover {
      /* Start the shake animation and make the animation last for 0.5 seconds */
      animation: shake 0.5s;

      /* When the animation is finished, start again */
      animation-iteration-count: infinite;
    }

    @keyframes shake {
      0% { transform: translate(1px, 1px) rotate(0deg); }
      10% { transform: translate(-1px, -2px) rotate(-1deg); }
      20% { transform: translate(-3px, 0px) rotate(1deg); }
      30% { transform: translate(3px, 2px) rotate(0deg); }
      40% { transform: translate(1px, -1px) rotate(1deg); }
      50% { transform: translate(-1px, 2px) rotate(-1deg); }
      60% { transform: translate(-3px, 1px) rotate(0deg); }
      70% { transform: translate(3px, 1px) rotate(-1deg); }
      80% { transform: translate(-1px, -1px) rotate(1deg); }
      90% { transform: translate(1px, 2px) rotate(0deg); }
      100% { transform: translate(1px, -2px) rotate(-1deg); }
    }
  </style>
  <title>{% block title %}{{ new.title }}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-md bg-light navbar-light">
  <a class="navbar-brand btn btn-link" href="{% url 'news:main' %}"><i class="fa fa-chevron-left fa-1x" aria-hidden="true"></i>Назад</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
  <main role="main">
    <div class="album py-5">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-2" ></div>
          <div class="col-sm-8">
            <img class="bd-placeholder-img card-img-top img-rounded" width="80%"  src="{{ new.picture }}">
            <div class="card-body">
              <a href="{{ new.site }}" target="_blank"><img class="mx-auto d-block logo" src="{{ new.logo }}" width="20%"></a>
              <hr width="80%" align="center">
              <p class="card-text"><h3 align="center"><b>{{new.title}}</b></h3></p>
              <p class="card-text">{{ new.description|safe|escape }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{ new }}</small>
              </div>
            </div>
          </div>
          <div class="col-sm-2"></div>
        </div>
      </div>
    </div>
  </main>
  <hr align="center" width="65%">
  <div class="container">
    <div class="row">
          {% for new in r_news %}
          <div class="col-sm-3">
            <div class="card mb-4 shadow-sm" style="max-width: 280px; max-height: 290px;">
              <a href="{% url 'news:post' new.id%}" target="_blank" id="myId"><img class="bd-placeholder-img card-img-top img-rounded" src="{{ new.picture }}" ></a>
              <a href="{{ new.site }}" target="_blank"><img class="mx-auto d-block logo" src="{{ new.logo }}" style="padding:2px;" width="35%"></a>
              <p class="card-text" style="padding: 1px;" align="center"><a href="{% url 'news:post' new.id %}" target="_blank"><h6 align="center"><b><small>{{new.title}}</small></b></h6></a></p>
            </div>
          </div>
          {% endfor %}
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

news/templates/news/search.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
    .logo:hover {
      /* Start the shake animation and make the animation last for 0.5 seconds */
      animation: shake 0.5s;

      /* When the animation is finished, start again */
      animation-iteration-count: infinite;
    }

    @keyframes shake {
      0% { transform: translate(1px, 1px) rotate(0deg); }
      10% { transform: translate(-1px, -2px) rotate(-1deg); }
      20% { transform: translate(-3px, 0px) rotate(1deg); }
      30% { transform: translate(3px, 2px) rotate(0deg); }
      40% { transform: translate(1px, -1px) rotate(1deg); }
      50% { transform: translate(-1px, 2px) rotate(-1deg); }
      60% { transform: translate(-3px, 1px) rotate(0deg); }
      70% { transform: translate(3px, 1px) rotate(-1deg); }
      80% { transform: translate(-1px, -1px) rotate(1deg); }
      90% { transform: translate(1px, 2px) rotate(0deg); }
      100% { transform: translate(1px, -2px) rotate(-1deg); }
    }
  </style>
  <title>{% block title %}Search{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-md bg-light navbar-light">
  <a class="navbar-brand btn btn-link" href="{% url 'news:main' %}"><i class="fa fa-chevron-left fa-1x" aria-hidden="true"></i>Назад</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
  <main role="main">
    <div class="album py-5">
      <div class="container">
        <div class="row">
                    <div class="col-md-2">
          </div>
          <div class="col-md-8">
            {% for i in news %}
                {% for new in i %}
            <div class="card mb-4 bg-light">
              <a href="{% url 'news:post' new.id %}"><img class="bd-placeholder-img card-img-top img-rounded" width="80%"  src="{{ new.picture }}"></a>
              <div class="card-body">
                <a href="{{ new.site }}" target="_blank"><img class="mx-auto d-block logo" src="{{ new.logo }}" width="40%"></a>
                <hr width="80%" align="center">
                <p class="card-text"><a href="{% url 'news:post' new.id %}" target="_blank"><h3 align="center"><b>{{new.title}}</b></h3></a></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href="{% url 'news:post' new.id %}" target="_blank"><button type="button" class="btn btn-sm btn-outline-secondary">Узнать больше</button></a>
                  </div>
                  <small class="text-muted">{{ new }}</small>
                </div>
              </div>
            </div>
                {% endfor %}
            {% endfor %}
          </div>
          <div class="col-md-2">
          </div>
        </div>
      </div>
    </div>
  </main>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>